### ISSUE TITLE
Add ColorSchemeCapability

### ISSUE THREAD

**Issue by j-o** [cginternals/gloperate#110]
It would be nice to have a capability to pass color schemes from the presets widget to a painter. The `widgetzeug::ColorScheme` class is based on Qt so it would probably be a good idea to port it to STL first to avoid the Qt dependency?
Where should this be implemented?

**Comment by scheibel** [comment]
We implemented our understanding of general color schemes / gradients in the ```ColorGradient``` class. A possible usage can be seen in https://github.com/cginternals/gloperate/blob/master/source/examples/globjects-painters/postprocessing/Postprocessing.cpp#L45 and the following lines.
Where the preset widget and possibly color scheme modification widgets come in is the configuration / provisioning of a ```ColorGradientList``` instance.

**Comment by sbusch42** [comment]
Will be implemented in gloperate 2.0
