### ISSUE TITLE
Undefined behavior in InputSlot::data(const T&)

### ISSUE THREAD

**Issue by p-otto** [cginternals/gloperate#141]
gloperate/source/gloperate/include/gloperate/pipeline/InputSlot.hpp

```cpp
template <typename T>
const T & InputSlot<T>::data(const T & defaultValue) const
{
    return isConnected() ? m_data->data() : defaultValue;
}
```

This causes undefined when called like foo(bar.data(1)), because the const & is out of scope for the foo call.

**Comment by sbusch42** [comment]
That depends on bar.data(), but if that returns a local value, this is of course invalid. Therefore, the example demonstrates a faulty use of the function, no error in the function itself. I don't see a way to solve this without copying data, which needs to be avoided (T can be a huge array!), so I close this. We should improve the documentation, though.
