### ISSUE TITLE
Refactor UI elements

### ISSUE THREAD

**Issue by sbusch42** [cginternals/gloperate#163]
Refactor the QML elements in gloperate
- Simplify Style (there are too many options in there)
- Make distinction between controls (mainly for dialogs) and elements on the main UI
- Simplify elements (e.g., menus and buttons)

**Comment by j-o** [comment]
While doing so, please avoid using the `QtGraphicalEffects` package, as it is based on GLSL 1.20 and therefore incompatible with core profile contexts. Currently, this affects only the `Icon` element.

Note: NVIDIA doesn't mind, but Intel does. See https://bugreports.qt.io/browse/QTBUG-42107

**Comment by sbusch42** [comment]
Ok, thank you for the remark. Any ideas on how to make a colored icon without ColorOverlay, then?

**Comment by sbusch42** [comment]
Created new issue #176 for that specific problem
