### ISSUE TITLE
Specify context as a command line parameter

### ISSUE THREAD

**Issue by sbusch42** [cginternals/gloperate#169]
Needs conversion functions context-description <-> string that can also be useful elsewhere

**Comment by scheibel** [comment]
Generic parameters of a context:
 * Type of client API (e.g., OpenGL, OpenGL ES, Vulkan, OpenVG)

We probably want to support OpenGL only for now. Further parameters:
* Major Version
* Minor Version
* Profile type
* Forward flag
* Debug flag
* Error flag (unfortunately not supported by Qt as of now but GLFW should be able to handle this)

**Comment by scheibel** [comment]
Closed with #317
