### ISSUE TITLE
Basic generic stages

### ISSUE THREAD

**Issue by sbusch42** [cginternals/gloperate#179]
Implement basic stages that can be used for rapid prototyping. This does not mean that they need to be used in larger projects!

Basic stages may include for example:
- Create/Load textures
- Create/Load geometry
- Create RenderTargets and FBOs
- Render geometry
- Select and mix RenderTargets
- Apply shader effects to RenderTargets

**Comment by scheibel** [comment]
This is a meta-issue. Each sub-task is addressed in a separate issue (or even multiple ones).
* Create/Load textures #201 #202 #13 
* Create/Load geometry
* Create RenderTargets and FBOs #177 #252 
* Render geometry #217 #45 #241 
* Select and mix RenderTargets
* Apply shader effects to RenderTargets #241
