### ISSUE TITLE
RenderPass should use the AbstractDrawable interface

### ISSUE THREAD

**Issue by j-o** [cginternals/gloperate#217]
Currently, `RenderPass` requires a `Drawable` object to specify the geometry; however, it only calls the `draw()` method from the `AbstractDrawable` interface on it.
Integration of specialized drawables (e.g., screen aligned quad) would be simpler, if `RenderPass` would require only an `AbstractDrawable`.

I suspect the problem is the use of `globjects::ref_ptr` to store the `m_geometry` member, which is incompatible with `AbstractDrawable`.

**Comment by scheibel** [comment]
We'll investigate.

**Comment by Jopyth** [comment]
Stumbled upon this issue too. Any decision on your preferred solution @scheibel ?

**Comment by j-o** [comment]
The problem is rooted in #232. Once that is resolved, this is merely a matter of find-and-replace.

**Comment by scheibel** [comment]
This is basically in progress now. It should be a side product of #270.
