### ISSUE TITLE
RenderPass::setTexture has no effect if a texture with the same index exists

### ISSUE THREAD

**Issue by j-o** [cginternals/gloperate#229]
`RenderPass` internally stores textures using an `unordered_map` and calls `emplace` to insert a Texture at a specific index. This means, that assigning a different Texture to the same index has no effect, since `emplace` (and `insert` as well) do not overwrite the associated values. The current workaround is to explicitly remove the old Texture by calling `removeTexture` prior to setting the new one.
Is this behavior intentional? I would expect the new texture would simply overwrite the old one.

Same goes for Sampler and Buffers.

**Comment by scheibel** [comment]
I suppose I misinterpreted the behavior of emplace. I'll provide a fix.

**Comment by j-o** [comment]
Closed with #230
