### ISSUE TITLE
Remove shared ownership for various graphics data types

### ISSUE THREAD

**Issue by cgcostume** [cginternals/gloperate#232]

**Comment by j-o** [comment]
This affects `Drawable`, `RenderPass`, `RenderTarget`. These are currently derived from `globjects::Referenced` and stored using `globjects::ref_ptr`. The current conevntion (?) is, that each of these is owned by the stage that created it and only non-owning pointers are passed via Slots. This does not require shared ownership semantics, instead `std::unique_ptr` can be used.

Investigate if this is the case for all affected types and implement the suggested solution.
