### ISSUE TITLE
AbstractCanvas::render vs. AbstractCanvas::onRender

### ISSUE THREAD

**Issue by j-o** [cginternals/gloperate#235]
The QML implementation calls `AbstractCanvas::render`, which in turn calls `AbstractCanvas::onRender`, while the Qt and GLFW implementations directly call `AbstractCanvas::onRender`.
Should they all call `AbstractCanvas::render`?

If yes, consider making `AbstractCanvas::onRender` private to avoid confusion.

**Comment by scheibel** [comment]
I think the default non-public visibility should be ```protected```.

**Comment by j-o** [comment]
Why?

**Comment by scheibel** [comment]
```protected``` visibility allows for usages in subclasses we cannot know.

**Comment by j-o** [comment]
That might be an argument for the default case, but for this concrete case, I would consider that an argument for making this private: `onRender` implements the customizable behavior of `render` and should therefore be called by this function only.
