### ISSUE TITLE
Conflicts between Debug and Release DLLs for plugins using MSVC

### ISSUE THREAD

**Issue by j-o** [cginternals/gloperate#237]
This might be a problem that should be solved in cpplocate, but I'll report it here for the concrete case of gloperate.

Using Visual Studio, a single build directory and solution file for all configurations (Debug, Release) is generated by cmake. In this build directory, two separate subdirectories exist for compiled  Debug and Release binaries. In addition, the following modinfo is generated and copied identically into both configuration subdirectories, pointing the plugin path at the entire build directory:
```
name: gloperate
version: 2.0.0
description: C++ library for defining and controlling modern GPU rendering/processing operations
author: CG Internals GmbH
dataPath: D:/projects/gloperate/data
pluginPath: D:/projects/gloperate/build
```

At runtime, gloperate loads its modinfo file, adds the plugin path to the `cppexpose::ComponentManager` and triggers plugin loading. The `ComponentManager` then recursively scans the entire build directory for `.dll` files, finds both Release and Debug versions of each plugin and tries to load them, resulting in some conflict and app crash.

I don't have a solution for this yet, here are some ideas that (probably) do not work:
1. Different modinfo files for Debug and Release: Complicated to implement (if at all possible), as there is no `CMAKE_BUILD_TYPE` variable when generating Visual Studio project files.
2. Preventing recursive scanning is not an option either, as the plugins are stored in subdirectories.

One idea might be to append either `/Debug` or `/Release` to the plugin path during scanning; however, this is very specific to the default Visual Studio build output structure (in addition, the default structure is different for x64 and x86 builds)

**Comment by j-o** [comment]
The question is: do we want to prevent plugin loading across different build types entirely, or just avoid loading the same library twice with different build types?

The first case could be handled by adding a `buildType` variable or function to the plugin interface (the one defined in `plugin_api.h`) and evaluate this before trying to initialize the plugin.

In the second case, we could add a unique plugin library identifier in a similar manner, that would remain equal across different build types of the same library. The `ComponentManager` could then use this identifier instead of the file path to identify a library. In this case, the `ComponentManager` should prefer plugin build types that match the applications build type, thus the search logic of `ComponentManager::scanPlugins` should be adjusted to first load all available plugin libraries, select the preferred build type and then initialize these.

**Comment by scheibel** [comment]
This issue is currently adressed in cppexpose: https://github.com/cginternals/cppexpose/pull/19
