### ISSUE TITLE
Remove non-const Slot::operator*

### ISSUE THREAD

**Issue by j-o** [cginternals/gloperate#257]
The non-const `Slot<T>::operator*` returns a mutable reference to the slot's value. This is problematic for two reasons:
1. Changing an Output's value through assignment of the returned reference (`*myOutput = 5;`) does not trigger the onValueChanged signal and does not set the valid flag, as `setValue` does.
2. Calling `operator*` on an Input returns a reference to the value stored in the Slot that the Input is connected to. Assigning a value to this reference thus modifies the Slot's value.

I suggest removing the non-const `operator*` entirely and perhaps add an `operator=(const T &)` instead with the same semantics as `setValue` to enable writing `myOutput = 5;`.

**Comment by scheibel** [comment]
Seems reasonable.
