### ISSUE TITLE
Investigate on default FBO of QtQuick

### ISSUE THREAD

**Issue by scheibel** [cginternals/gloperate#280]
Probably the default FBO of QtQuick should be used as the default framebuffer for our qml-based viewer.
Sources:
* http://doc.qt.io/qt-5/qtquick-visualcanvas-scenegraph.html#mixing-scene-graph-and-opengl
* http://doc.qt.io/qt-5/qtquick-scenegraph-textureinsgnode-example.html
* http://doc.qt.io/qt-5/qtquick-scenegraph-textureinthread-example.html

**Comment by sbusch42** [comment]
I don't know what you meant by "default FBO", but we're rendering into FBOs now with QtQuick instead of the direct rendering method we used before.

**Comment by scheibel** [comment]
I think this suffices.
