### ISSUE TITLE
Use loader and stages without plugin

### ISSUE THREAD

**Issue by scheibel** [cginternals/gloperate#282]
Use static initialization to register loader and stages and provide an interface on ComponentManager to load statically initialized components.

Tasks:

Extend ComponentManager to manage statically instantiated components
* [ ] Register function ```ComponentManager::registerStaticComponent```
* [ ] Static list of Components ```std::vector<Component *>``` defined in scope of accessor (see next line)
* [ ] Accessor returning (const) reference to static list of components

Automatic registration of static components
* [ ] Add static component instantiatior calling the ```registerStaticComponent``` with given component
* [ ] Extend ```CPPEXPOSE_COMPONENT``` macro to instantiate the static component instantiator (see previous line)

Remove registerLocalPlugin interface and behavior (refs #278)
* [ ] Remove ```Environment::registerLocalPlugins()```

**Comment by scheibel** [comment]
@sbusch42 @j-o can you review my approach?

**Comment by j-o** [comment]
I thinks this conflicts with loading components from actual plugins. Loading the plugin library causes the static instantiator to be executed (?) which registers the component. Then, the `ComponentManager` iterates over all the plugin's components, registering them again. I see two solutions: provide a `CPPEXPOSE_STATIC_COMPONENT` or rely on the static instatiator for plugins as well and remove the explicit registration.

Should this be in gloperate or cppexpose?

**Comment by sbusch42** [comment]
Yes, exactly. I would rather not have plugins to register themselves automatically, so we should provide a separate macro as you proposed, used for static components. And that should of course be in cppexpose, as the whole component system is defined in cppexpose.
