### ISSUE TITLE
Compile error with Flags template on apple clang

### ISSUE THREAD

**Issue by sbusch42** [cginternals/gloperate#356]
With the new Flags template, apple clang is confused:

/workspace/projects/cginternals/gloperate/source/examples/demo-stages-plugins/DemoStage.cpp:113:41: error: use of overloaded operator '|' is ambiguous (with operand types 'const       glbinding::SharedBitfield<AttribMask, ClearBufferMask>' and 'const       glbinding::SharedBitfield<AttribMask, ClearBufferMask>')     gl::glClear(gl::GL_COLOR_BUFFER_BIT | gl::GL_DEPTH_BUFFER_BIT);

/workspace/projects/cginternals/cppassist/source/cppassist/include/cppassist/flags/Flags.inl:59:28: note: candidate function [with EnumType = glbinding::SharedBitfield<gl::AttribMask, gl::ClearBufferMask>] cppassist::Flags<EnumType> operator|(EnumType flag1, EnumType flag2)

/workspace/projects/cginternals/glbinding/source/glbinding/include/glbinding/SharedBitfield.h:374:37: note: candidate function [with T = <gl::AttribMask, gl::ClearBufferMask>] GLBINDING_CONSTEXPR inline auto operator|(SharedBitfield<T...> other...

/workspace/projects/cginternals/glbinding/source/glbinding/include/glbinding/gl/types.h:287:39: note:       candidate function GLBINDING_CONSTEXPR inline AttribMask operator|(const AttribMask & a, co...                                       

/workspace/projects/cginternals/glbinding/source/glbinding/include/glbinding/gl/types.h:359:44: note:       candidate function GLBINDING_CONSTEXPR inline ClearBufferMask operator|(const ClearBufferMa...                                            ^ 1 error generated.

**Comment by scheibel** [comment]
Clang on Linux is affected, too.

**Comment by scheibel** [comment]
I opened a PR in cppassist: https://github.com/cginternals/cppassist/pull/37
