### ISSUE TITLE
Pass options to a Loader

### ISSUE THREAD

**Issue by j-o** [cginternals/gloperate#42]
I'm not sure what the best solution for the generic case is, perhaps using a `map<string, string>`?

Current use case: I want to load textures with compression, so I need a way to specify the texture's internal format.

**Comment by scheibel** [comment]
The current API of gloperate actually supports this: https://github.com/cginternals/gloperate/blob/master/source/gloperate/include/gloperate/resources/Loader.h#L53 (don't know for how long).
