### ISSUE TITLE
Add RenderPass utility class

### ISSUE THREAD

**Issue by scheibel** [cginternals/gloperate#45]
A RenderPass class should collect all information necessary to execute a specific OpenGL draw call with all it's required bindings and should provide the functionality to execute the specified render pass.
Therefor, a RenderPass should be configured with the following information:
 * VAO
 * Draw call, mode, ranges, ...
 * Program
 * State changes
 * Textures
 * Buffers (Uniform buffers, SSBO, Atomic buffers, Transform feedback buffers, ...)

Did I miss some OpenGL state?
I think it is arguable if the FBO and current Viewport are part of a RenderPass. I think they should not be part of this class.

**Comment by sbusch42** [comment]
Shall this class also execute the specific OpenGL call, or only contain the state needed for the render pass? In the former case, I see a resemblence to a render stage (AbstractStage), in the latter case, why not use globjects state classes? I have the feeling this somehow duplicates what is already there.

**Comment by scheibel** [comment]
Actually I thought about something like
```c++
// Configuration
gloperate::RenderPass * pass = new gloperate::RenderPass();
pass->configureForInstancedCall(GL_POINTS, 0, m_vertices.size(), count);
pass->useVAO(m_vao);
pass->useProgram(m_program);
pass->useTexture(m_texture, GL_TEXTURE0);
pass->useBuffer(m_buffer, GL_SHADER_STORAGE_BUFFER, 0);
pass->useState(m_state);

// Rendering

pass->render();
```
So yeah, globjects' ```State``` class is used as an internal part and I would like to execute the render pass directly through the ```RenderPass``` object.

**Comment by scheibel** [comment]
If I think further and take our current designs into account, it is questionable if the ```RenderPass::render``` method should or may take additional arguments...each of the lines above are arguably useful parameters for temporal variations.
Considering this, the one goal of this class would be the reduction of source code for the gloperate client code.

Ultimately, with the introduction of explicit OpenGL command lists I think this class can provide much more functionality and even performance improvements.
See: https://www.opengl.org/discussion_boards/showthread.php/185515-NV_command_list, http://de.slideshare.net/tlorach/opengl-nvidia-commandlistapproaching-zerodriveroverhead

**Comment by scheibel** [comment]
And I still don't know what interface I would want for more complex render passes (e.g., conditional rendering, occlusion queries, non-OpenGL-3.2-core render pass implementations, compound render passes, ...).

**Comment by scheibel** [comment]
Just to boost the significance of this class:
> A key feature added to Vulkan is the render pass, which redefines how well an application can control our hardware, and reduces the amount of work we have to do implicitly without the application necessarily knowing about it.
(Source: http://blog.imgtec.com/powervr/trying-out-the-new-vulkan-graphics-api-on-powervr-gpus)

**Comment by j-o** [comment]
What about compute passes? Should they be supported as well?

**Comment by scheibel** [comment]
Compute passes should be a concept in gloperate, but I think the name ```RenderPass``` states that it has nearly nothing to do with computing. However, the current ```RenderPass``` implementation supports transform feedbacks and this concept is almost always used for computing passes.

I suggest that compute passes are handled with another class.

**Comment by scheibel** [comment]
I also think this issue can be closed, as https://github.com/cginternals/gloperate/pull/158 is merged.
