### ISSUE TITLE
Repaint capability

### ISSUE THREAD

**Issue by scheibel** [cginternals/gloperate#61]
Capabilities are the communication objects between a ```Painter``` and, e.g., a ```Viewer```.
Therefore, they are used to either tell the ```Painter``` what to do or the ```Viewer``` what to do.

When it comes to a static rendering, the ```Viewer``` normally knows when it's best to repaint the canvas. With a dynamic painting in terms of animation, the ```AbstractVirtualTimeCapability``` can be used so that the ```Viewer``` tells the ```Painter``` how much time has passed and the ```Viewer``` knows through the availability of this specific capability, that the ```Painter``` wants to repaint continuously.
When it comes to time-dependent (and ending) animations or progressive image synthesis, the ```Painter``` don't want to repaint continuously but wants to repaint a specific amount of times.
Sometimes, the ```Painter``` doesn't even know how often it wants to repaint (e.g., if it is dependent on the visible delta of the frame before), so the it only wants to communicate to be called *at least once more*.

Therefore, I propose the ```AbstractRepaintCapability``` that should enable the communication between ```Viewer``` and ```Painter``` when it comes to limited but not trivial (>1) repaints.

Class excerpt:
```cpp
class GLOPERATE_API AbstractRepaintCapability : public AbstractCapability
{
public:
    AbstractRepaintCapability();
    virtual ~AbstractRepaintCapability();

    virtual bool wantsRepaint() const = 0;
};

class GLOPERATE_API RepaintCapability : public AbstractRepaintCapability
{
public:
    RepaintCapability();

    virtual bool wantsRepaint() const override;
    setWantsRepaint(bool on);
protected:
    bool m_wantsRepaint;
};
```

**Comment by sbusch42** [comment]
Should be possible with gloperate 2.0 through the signal redraw() (canvas) and the output 'rendered' (pipeline)
