### ISSUE TITLE
Incorrect cast in SystemApi on key press

### ISSUE THREAD

**Issue by PFischbeck** [cginternals/gloperate#90]
In https://github.com/cginternals/gloperate/blob/master/source/gloperate-qt/source/scripting/SystemApi.cpp#L139, a cast to char throws a Runtime Check Failure when pressing certain keys, e.g. Tab, Ctrl or arrow keys.
`keyPressed(QString() + (char)keyEvent->key());`
This is because some key values are larger than char.
http://doc.qt.io/qt-5/qt.html#Key-enum
Applying a bitmask for the last byte won't work either, as this would lead to incorrect conversion.

What would be the right fix here? Checking the key for a certain range?

**Comment by sbusch42** [comment]
Should be invalid for gloperate 2.0, since key events are not exposed to scripting like this any more
